branches: master

pipeline:
  publish:
    image: node
    secrets: [ azure_storage_account, azure_storage_access_key ]
    environment:
      - AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT
      - AZURE_STORAGE_ACCESS_KEY=$AZURE_STORAGE_ACCESS_KEY
    commands:
      - npm install
      - npm run build
      - npm run deploy

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: build
    username: Drone
    when:
      status: [ success, failure ]
